### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by chrisrng** [pricelinelabs/omni-slider#22]
```
> gulp deploy

[13:26:36] Requiring external module babel-register
module.js:329
    throw err;
    ^

Error: Cannot find module 'gulp-jshint'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (build.js:8:1)
    at Module._compile (module.js:399:26)
    at loader (/Users/XXXXX/omni-slider/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/XXXXX/omni-slider/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! omni-slider@1.2.0 deploy: `gulp deploy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the omni-slider@1.2.0 deploy script 'gulp deploy'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the omni-slider package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp deploy
npm ERR! You can get their info via:
npm ERR!     npm owner ls omni-slider
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/XXXXXX/Desktop/omni-slider/npm-debug.log
```

**Comment by chrisrng** [comment]
Missing dependencies and the branch `gh-pages` was deleted. Activity log did not return any result on how it was deleted
